## Main parameter of this model:

model_name: Global_EXC_30Hz_smoothing50ms_causalkernel # Name of the model
sampling_rate: 30                             # Sampling rate in Hz

# Dataset of ground truth data (in folder 'Ground_truth')   Example: DS13-GCaMP6s-m-V1
training_datasets:
- DS02-Cal520-m-S1
- DS03-OGB1-zf-pDp
- DS04-Cal520-zf-pDp
- DS05-GCaMP6f-zf-aDp
- DS06-GCaMP6f-zf-dD
- DS07-GCaMP6f-zf-OB
- DS08-GCaMP6f-m-V1
- DS09-GCaMP6f-m-V1-neuropil-corrected
- DS10-GCaMP6f-m-V1-neuropil-corrected
- DS11-GCaMP6s-m-V1-neuropil-corrected
- DS12-GCaMP6s-m-V1-neuropil-corrected
- DS13-GCaMP6s-m-V1
- DS14-GCaMP6s-m-V1
- DS15-GCaMP6s-m-V1
- DS16-GCaMP5k-m-V1
- DS17-R-CaMP-m-CA3
- DS18-R-CaMP-m-S1
- DS19-jRCaMP1a-m-V1
placeholder_1: 0       # protect formatting


# Noise levels for training (integers, normally 1-9)
noise_levels:
- 2
- 3
- 4
- 5
- 6
- 7
- 8
placeholder_2: 0       # protect formatting


# Standard deviation of Gaussian smoothing in time (sec)
smoothing: 0.05

# Smoothing kernel is symmetric in time (0) or is causal (1)
causal_kernel: 1

## Additional parameters for model specification:


windowsize: 64                   # Windowsize in timepoints
before_frac: 0.5                 # Fraction of timepoints before prediction point (0-1)

# Filter sizes for each convolutional layer
filter_sizes:
- 31
- 19
- 5

# Filter numbers for each convolutional layer
filter_numbers:
- 30
- 40
- 50

dense_expansion: 30              # For dense layer


loss_function: mean_squared_error     # gradient-descent loss function
optimizer: Adagrad                    #                  optimizer

nr_of_epochs: 10                 # Number of training epochs per model
ensemble_size: 5                 # Number of models trained for one noise level
batch_size: 8192                 # Batch size

## Information about status of fitting

training_finished: Yes           # Yes / No / Running
verbose: 1                       # level of status messages (0: minimal, 1: standard, 2: most, 3: all)


## Additional parameter not specified in template

